### ISSUE TITLE
No instruction how to set Access ID and Access Key for EgoExo4D

### ISSUE THREAD

**Issue by isarandi** [facebookresearch/Ego4d#277]
How do you use the given Access ID and Access Key you get after approval? It's not explained in any readme or documentation I found on the website or the repo. Running `egoexo --help` also does not mention anything related to configuring access.

If I just run `egoexo -o ./ --parts annotations metadata`, I just get an exception `botocore.exceptions.ProfileNotFound: The config profile (default) could not be found`.

I assume I need to edit some config file or some environment variable, or some S3 profile file or something?
Thanks!

**Comment by isarandi** [comment]
Okay, I figured it out by reading AWS docs.

Save to the `~/.aws/credentials` file the following content:

```
[default]
aws_access_key_id=...
aws_secret_access_key=...
```

But it would be useful to add this to the docs somewhere.

**Comment by miguelmartin75** [comment]
Yes agreed, apologies for not including this detail.

You can alternatively run `aws configure` (`pip install awscli`), enter your keys and then press enter twice to use the defaults for the region name and output format.

**Comment by miguelmartin75** [comment]
This is now documented: https://docs.ego-exo4d-data.org/download/#setup-aws-client

**Comment by richardrl** [comment]
I got this error:
ERROR: could not get manifests for all parts (nothing to download)
Did you supply the right parts?
NOTE: Did you configure your AWS client correctly? See: https://github.com/facebookresearch/Ego4d/issues/277

This could also be due to your internet connection.

If you are located in China, please try using a VPN. Please refer to these posts:
- https://github.com/facebookresearch/Ego4d/issues/223
- https://github.com/facebookresearch/Ego4d/issues/162
- https://github.com/facebookresearch/Ego4d/issues/284


Fixed it by renewing license key

**Comment by wz940828** [comment]
秘钥怎么申请啊
