### ISSUE TITLE
Can't read and play videos in gaze dataset and can't find gaze labels

### ISSUE THREAD

**Issue by LAIBOLIN** [facebookresearch/Ego4d#82]
Hi Ego4d team,

Thanks for the dataset.

I'm trying to download videos with gaze annotations. Following the instructions in [official website](https://ego4d-data.org/docs/data/gaze/), I should download them using the command `python3 -m ego4d.cli.cli --output_directory=/Data/Ego4D --datasets gaze`. I downloaded all gaze data, but I failed to play them. There's an error - 'The file isn’t compatible with QuickTime Player'. I wonder whether those videos have been damaged.

As for the annotation, the official document shows some samples of gaze annotations in csv, but I can't find it after downloading gaze dataset. Could you tell me how to obtain them?

I have posted these issues twice (#79 #54 ), but they were closed and the issues are still unsovled. Some replies even conflict with the instructions on official website. I can't reopen them, so I post this new issue. I really need those data and labels to continue my research. I would appreciate it if you keep this issue open until it's addressed.

Thank you in advance.

**Comment by LAIBOLIN** [comment]
I checked files in `<download_dir>/v1/gaze` again. All suffixes are `.mp4`. That's why I tried to open them using a video player. I can open them using vim now, so I think this is a typo. You save those CSV files with suffix `.mp4`. I'll double check associated videos later.

**Comment by ebyrne** [comment]
@LAIBOLIN Appreciate you pointing that out and your patience!

That was an error on how the manifest for `gaze` was configured.  Please delete the existing directory and try downloading again, it will come down as a csv file.

And I'll leave this open until it's good on your end, sorry you had to repost.  (I believe Github doesn't allow you to reopen unless you're a collaborator on the repo, that's why you can't reopen here, not a setting I can change I believe.)

Thanks again for contributing to Ego4D!

**Comment by LAIBOLIN** [comment]
Thanks for your help. I downloaded gaze annotations successfully. I want to know how to get the corresponding videos. I downloaded AV benchmark, but found none of them was labeled with gaze. I wonder under which benchmark I can get those  labeled videos.
