### ISSUE TITLE
Hand Bounding Boxes

### ISSUE THREAD

**Issue by leonardirosario97** [facebookresearch/Ego4d#84]
Hi Ego4d team,

Thanks for the dataset, it's great! 
I have a doubt regarding the hand annotations in the "fho_hands.json" file.

The documentation seems to indicate the presence of the bounding boxes of the hands (https://ego4d-data.org/docs/benchmarks/hands-and-objects/), but in my annotation files I have something like this:
![image](https://user-images.githubusercontent.com/37408992/160841072-c555916f-b12e-45fe-bb65-f212b02b658d.png)

In which each box of a hand is represented by an array of two elements, while I would have expected an array of four elements (x0, y0, w, h) to indicate the bounding box.

Am I doing something wrong?

Thank you in advance.

**Comment by ebyrne** [comment]
That's correct.  For FHO Hands specifically, they chose to represent it as a single point rather than a bounding box (at the center).  Most everywhere else you will find four element bounding boxes.  We can add a note to that effect in the docs.

If you wanted to follow up with them on further questions, please post those to the benchmark specific repo: https://github.com/EGO4D/hands-and-objects/

Thanks for participating in Ego4d @leonardirosario97!

**Comment by Seleucia** [comment]
This should be definitely corrected in documentation. It is misleading information.  I have been expecting bounding for hand.
